### ISSUE TITLE
Error after flutter upgrade

### ISSUE THREAD

**Issue by BerkSpar** [Flutterando/slidy#191] opened 2020-08-07 04:34 UTC
I upgraded to the last version of Flutter and Slidy doesn't work after that. When I try to use any command on Slidy it returns:

```
Can't load Kernel binary: Invalid kernel binary format version.
```

My Flutter version:

```
[√] Flutter (Channel stable, 1.20.1, on Microsoft Windows [versÃ£o 10.0.18362.959], locale pt-BR)
    • Flutter version 1.20.1 at C:\src\flutter
    • Framework revision 2ae34518b8 (26 hours ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0
```

Note: I also upgraded Dart SDK.
Note 2: I also reinstaled Slidy.

**Comment by andrewbiller** [comment] 2020-08-07 18:50
I removed **flutter\bin\cache**

Upgraded the standalone dart installation to 2.90 (stable)

Then, I ran **flutter doctor** again.

The error has gone, but when I run **slidy --version** it closes the window (prompt or terminal tab at android studio)

`Slidy version: 2.1.2+2`

**Comment by GabrielCR99** [comment] 2020-08-12 13:46
In **Windows**, what I did to fix this was, open the **Run** command window with Windows + R key, then type %appdata%. There, assuming you're in the Roaming folder, go to Pub\Cache\hosted\pub.dartlang.org, there, you'll find all of the cached slidy packages. I deleted them all (had about 3, with different version installed).
Then, installed slidy.
When I ran **slidy --version**, it showed up normally without closing any prompt/terminal tab.
Hope it wors for you all!

**Comment by toshiossada** [comment] 2020-08-12 15:23
@GabrielCR99  doesnt works to me

**Comment by andrewbiller** [comment] 2020-08-12 16:30
The problem is the **slidy.bat** inside Pub\Cache\bin

**Comment by BerkSpar** [comment] 2020-08-13 12:08
I fixed the problem doing these steps:
* Uninstalling slidy
```cmd
flutter pub global deactivate slidy
pub global deactivate slidy
```
* Forcing dart to a old version
```cmd
choco uninstall dart-sdk
choco install dart-sdk --version 2.8.4
```
* Running flutter upgrade
```cmd
flutter upgrade
```
* Reinstaling slidy
```cmd
pub global activate slidy
```

Versions:
```cmd
C:\Windows\System32>slidy --version

███████╗██╗     ██╗██████╗ ██╗   ██╗     ██████╗██╗     ██╗
██╔════╝██║     ██║██╔══██╗╚██╗ ██╔╝    ██╔════╝██║     ██║
███████╗██║     ██║██║  ██║ ╚████╔╝     ██║     ██║     ██║
╚════██║██║     ██║██║  ██║  ╚██╔╝      ██║     ██║     ██║
███████║███████╗██║██████╔╝   ██║       ╚██████╗███████╗██║
╚══════╝╚══════╝╚═╝╚═════╝    ╚═╝        ╚═════╝╚══════╝╚═╝

CLI package manager and template for Flutter

Slidy version: 2.1.2+2

C:\Windows\System32>pub --version
Pub 2.8.4

C:\Windows\System32>flutter --version
Flutter 1.20.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2ae34518b8 (7 days ago) • 2020-08-05 19:53:19 -0700
Engine • revision c8e3b94853
Tools • Dart 2.9.0
```

note: Inside path enviroment put dart-sdk on the top.

**Closed** 2020-08-24 14:18 UTC
